#!/bin/bash

###########
#Calculator
#Author: Gayathri
#Version: 1
###########
#
set -x

echo "This is a simple calculator that adds two numbers"
echo "Enter ur first num: "
read n1
echo "Enter ur second num: "
read n2

let sum=($n1 + $n2)
echo $sum " is the result"
